site_name: packages/migration-lint
site_url: https://pandadoc.github.io/migration-lint/

repo_name: pandadoc/migration-lint
repo_url: https://github.com/pandadoc/migration-lint

theme:
  name: material
  custom_dir: docs-theme
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:migration-lint-team@pandadoc.com
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets

plugins:
  - search
  - tags:
      tags_file: tags.md

nav:
  - Welcome: index.md
  - Rules API: rules.md
  - Migration classification: classification.md
